use_frameworks!

target 'CCCircularProgressView-Swift_Example' do
  pod 'CCCircularProgressView-Swift', :path => '../'

  target 'CCCircularProgressView-Swift_Tests' do
    inherit! :search_paths

    
  end
end
